apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deploy-__tag__
spec:
  selector:
    matchLabels:
      app: __appName__-__tag__
  replicas: __kub-pod-instancecount__
  template:
    metadata:
      labels:
        app: __appName__-__tag__
    spec:
      containers:
      - name: pipelines-javascript-k8s-__tag__
        image: ezlee/__imageName__:__tag__
        ports:
        - containerPort: 80
